### ISSUE TITLE
Example of data to supply in params.env when using Windows

### ISSUE THREAD

**Issue by SimonKravis** [zaandahl/mewc#3]
What data needs to appear in the params.env file specified in the Powershell examples? Is it simply the text below?

MODEL=EN-V2S
CLW=512
LUF=360
SHAPES=300,300,300
BATCH_SIZES=128,128,128

**Comment by SimonKravis** [comment]
What should be in the files class_list.yaml and my_classifier_model.h5?

 C:\mewc\ps\mewc_run_service.ps1 -i C:\example -p C:\mewc\model\params.env -c C:\mewc\yaml\class_list.yaml -m C:\mewc\model\my_classifier_model.h5 -g 0

**Comment by zaandahl** [comment]
The data that you supply to the params.env environment file is dependent on which tool you are running. Each of the GitHub pages has a table with the possible environmental variables and their default values. 

The env variables you are asking about deal with EfficientNet classification and the code and documentation can be found at https://github.com/zaandahl/mewc-train and https://github.com/zaandahl/mewc-predict. 

The initial pipeline for training would consist of taking your training images through the following steps:

mews-detect -> mewc-snip -> separate snips into labeled classes for training -> mewc-train

After this you can perform inference on new images using mewc-predict. This step will use a trained h5 model and class_list.yaml file that are produced by mew-train from the previous training step. 

mews-detect -> mewc-snip -> mewc-predict

The names for these files are arbitrary and are determined by the arguments you pass to the PowerShell scripts.

Please let me know if this explanation helps. 

Best,
Zach

**Comment by SimonKravis** [comment]
Dear Zach

 

Thank you for your prompt and helpful reply. When I try to run mewc_detect get the output below and no process appears to be executing. Powershell needs to have Set-Execution-Policy Bypass executed in order to run an unsigned script. Docker Desktop also needs to be running. The target folder  "C:\Users\simon\OneDrive\Pictures\Camera Trap\Fox Crow Training" contains a number of training jpg images and other files. The params.env file is as below.

 

Any advice you can give would be most welcome.

 

Regards

Simon Kravis

 

 

 

PS C:\Users\simon\OneDrive\Documents\mewc> C:\Users\simon\OneDrive\Documents\mewc\mewc_run_detect.ps1 -i "C:\Users\simon\OneDrive\Pictures\Camera Trap\Fox Crow Training" -p C:\users\simon\OneDrive\Documents\mewc\params.env -g 0

Using default tag: latest

latest: Pulling from zaandahl/mewc-detect

Digest: sha256:0b7d71b87f9a14d0b5ebce4e281f2f36e5d72c33977560dbfbb4d4812133b35b

Status: Image is up to date for zaandahl/mewc-detect:latest

docker.io/zaandahl/mewc-detect:latest

 

What's Next?

  View a summary of image vulnerabilities and recommendations → docker scout quickview zaandahl/mewc-detect

PS C:\Users\simon\OneDrive\Documents\mewc>

 

Params.env content

 

MODEL=EN-V2S

CLW=512

LUF=360

SHAPES=300,300,300

BATCH_SIZES=128,128,128

**Comment by zaandahl** [comment]
Hi Simon, 

You can try starting the Docker container directly without the PowerShell script to see if it runs correctly. This will rule out if there are problems with the script or if the container is having trouble processing your images. Make sure your images are not nested in Fox Crow Training as the MegaDetector container only reads one level deep I think.

`docker run --env CUDA_VISIBLE_DEVICES=0 --gpus all --volume "C:\Users\simon\OneDrive\Pictures\Camera Trap\Fox Crow Training":/images --env-file "C:\users\simon\OneDrive\Documents\mewc\params.env" zaandahl/mewc-detect`

Please let me know if this works and if it doesn't let me know what the output is. Also make sure that you are running Windows 11 or a current version of Windows 10, you have current Nvidia drivers installed on your machine and the Docker Desktop is the latest version. 

Best,
Zach
